+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon May 26 07:58:51 2025 - INFO  - Start to prepare the test environment.
+ pip3 install fake_useragent
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))': /simple/fake-useragent/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f163bafb550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/fake-useragent/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))': /simple/fake-useragent/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))': /simple/fake-useragent/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))': /simple/fake-useragent/
Could not fetch URL https://pypi.org/simple/fake-useragent/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/fake-useragent/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))) - skipping
ERROR: Could not find a version that satisfies the requirement fake_useragent (from versions: none)
ERROR: No matching distribution found for fake_useragent
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)'))) - skipping
WARNING: There was an error checking the latest version of pip.
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon May 26 08:01:01 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon May 26 08:01:01 2025 - INFO  - Start to run test.
+ expect
spawn python3
Python 3.10.9 (main, Mar 27 2023, 23:05:54) [GCC 10.3.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> import urllib.request
>>> import fake_useragent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fake_useragent'
>>> from fake_useragent import UserAgent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fake_useragent'
>>> ua = UserAgent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'UserAgent' is not defined
>>> headers = {'User-Agent': ua.random}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ua' is not defined
>>> url = 'https://www.baidu.com/'
>>> request = urllib.request.Request(url=url, headers=headers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'headers' is not defined
>>> response = urllib.request.urlopen(request)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'request' is not defined
>>> response.read().decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'response' is not defined
>>> response.getcode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'response' is not defined
>>> exit()
+ grep -E 'data|body|html' testlog
+ CHECK_RESULT 1 0 0 'Data return failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Data return failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Data return failed'
+ LOG_ERROR 'Data return failed'
+ message='Data return failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Data return failed'
Mon May 26 08:01:01 2025 - ERROR - Data return failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_python_urllib3_urlopen_02.sh line 48'
+ message='oe_test_python_urllib3_urlopen_02.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_python_urllib3_urlopen_02.sh line 48'
Mon May 26 08:01:01 2025 - ERROR - oe_test_python_urllib3_urlopen_02.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep -A 3 response.getcode testlog
+ grep 200
+ CHECK_RESULT 1 0 0 'Status code return failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Status code return failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Status code return failed'
+ LOG_ERROR 'Status code return failed'
+ message='Status code return failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Status code return failed'
Mon May 26 08:01:01 2025 - ERROR - Status code return failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_python_urllib3_urlopen_02.sh line 50'
+ message='oe_test_python_urllib3_urlopen_02.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_python_urllib3_urlopen_02.sh line 50'
Mon May 26 08:01:01 2025 - ERROR - oe_test_python_urllib3_urlopen_02.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon May 26 08:01:01 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon May 26 08:01:01 2025 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon May 26 08:01:01 2025 - INFO  - Start to restore the test environment.
+ rm -rf testlog
+ pip3 uninstall fake_useragent -y
WARNING: Skipping fake_useragent as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon May 26 08:01:02 2025 - INFO  - End to restore the test environment.
