+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ source ./common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ ARRAY_PROFILE=("arm-native-android-container-robox" "basic-test-suite-baseline-fio" "basic-test-suite-baseline-lmbench" "basic-test-suite-baseline-netperf" "basic-test-suite-baseline-stream" "basic-test-suite-baseline-unixbench" "basic-test-suite-speccpu-speccpu2006" "basic-test-suite-specjbb-specjbb2015" "big-data-hadoop-hdfs-dfsio-hdd" "big-data-hadoop-hdfs-dfsio-ssd" "big-data-hadoop-spark-bayesian" "big-data-hadoop-spark-kmeans" "big-data-hadoop-spark-sql1" "big-data-hadoop-spark-sql10" "big-data-hadoop-spark-sql2" "big-data-hadoop-spark-sql3" "big-data-hadoop-spark-sql4" "big-data-hadoop-spark-sql5" "big-data-hadoop-spark-sql6" "big-data-hadoop-spark-sql7" "big-data-hadoop-spark-sql8" "big-data-hadoop-spark-sql9" "big-data-hadoop-spark-tersort" "big-data-hadoop-spark-wordcount" "cloud-compute-kvm-host" "database-mariadb-2p-tpcc-c3" "database-mariadb-4p-tpcc-c3" "database-mongodb-2p-sysbench" "database-mysql-2p-sysbench-hdd" "database-mysql-2p-sysbench-ssd" "database-postgresql-2p-sysbench-hdd" "database-postgresql-2p-sysbench-ssd" "default-default" "docker-mariadb-2p-tpcc-c3" "docker-mariadb-4p-tpcc-c3" "hpc-gatk4-human-genome" "in-memory-database-redis-redis-benchmark" "middleware-dubbo-dubbo-benchmark" "storage-ceph-vdbench-hdd" "storage-ceph-vdbench-ssd" "virtualization-consumer-cloud-olc" "virtualization-mariadb-2p-tpcc-c3" "virtualization-mariadb-4p-tpcc-c3" "web-apache-traffic-server-spirent-pingpo" "web-nginx-http-long-connection" "web-nginx-https-short-connection")
++ ARRAY_SERVICE=("arm-native" "basic-test-suite" "big-data" "cloud-compute" "database" "default" "docker" "hpc" "in-memory-database" "middleware" "storage" "virtualization" "web")
++ SPECIAL_CHARACTERS='~\!@#%^*'
++ ULTRA_LONG_CHARACTERS=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu May 25 22:14:51 2023 - INFO  - Start environment preparation.
+ deploy_autund
+ DNF_INSTALL 'atune  atune-engine'
+ pkgs='atune  atune-engine'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'atune  atune-engine' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpbk8ahrtn
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpbk8ahrtn
++ lsblk
++ grep disk
++ awk 'NR==1{print $1}'
+ disk_name=vda
+ cp /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf.bak
+ cp /etc/atuned/engine.cnf /etc/atuned/engine.cnf.bak
+ sed -i 's/^disk =.*/disk = vda/g' /etc/atuned/atuned.cnf
+ sed -i 's/^network =.*/network = /g' /etc/atuned/atuned.cnf
+ sed -i 's/rest_tls = true/rest_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/engine.cnf
+ creat_ca
+ CERT_PATH=demo
+ mkdir demo
+ openssl genrsa -out demo/ca.key 2048
+ openssl req -new -x509 -days 3650 -subj /CN=ca -key demo/ca.key -out demo/ca.crt
+ IP_ADDR=localhost
+ openssl genrsa -out demo/server.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/server.key -out demo/server.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/server.csr -out demo/server.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/server.csr demo/extfile.cnf demo/openssl.cnf
+ IP_ADDR=localhost
+ openssl genrsa -out demo/client.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/client.key -out demo/client.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/client.csr -out demo/client.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/client.csr demo/extfile.cnf demo/openssl.cnf
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/rest_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/client.crt demo/client.key /etc/atuned/engine_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/engine_certs/
+ systemctl start atuned
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ systemctl status atuned
+ grep running
+ CHECK_RESULT 1 0 0 'atuned service startup failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned service startup failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned service startup failure'
+ LOG_ERROR 'atuned service startup failure'
+ message='atuned service startup failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atuned service startup failure'
Thu May 25 22:21:05 2023 - ERROR - atuned service startup failure
+ (( exec_result++ ))
+ LOG_ERROR './common/common_lib.sh line 40'
+ message='./common/common_lib.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message './common/common_lib.sh line 40'
Thu May 25 22:21:05 2023 - ERROR - ./common/common_lib.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start atune-engine
+ systemctl status atune-engine
+ grep running
     Active: active (running) since Thu 2023-05-25 22:13:54 CST; 7min ago
+ CHECK_RESULT 0 0 0 'atune-engine service startup failure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine service startup failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu May 25 22:21:06 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ (( i=0 ))
+ (( i<46 ))
+ atune-adm info arm-native-android-container-robox
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:07 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:08 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-baseline-fio
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:09 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:09 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-baseline-lmbench
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:10 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:10 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-baseline-netperf
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:11 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:12 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-baseline-stream
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:13 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:13 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-baseline-unixbench
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:14 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:15 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-speccpu-speccpu2006
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:15 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:16 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info basic-test-suite-specjbb-specjbb2015
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:17 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:17 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-hdfs-dfsio-hdd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:18 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:19 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-hdfs-dfsio-ssd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:20 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:20 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-bayesian
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:21 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:22 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-kmeans
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:22 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:23 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql1
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:24 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:24 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql10
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:25 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:26 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql2
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:27 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:27 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:28 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:29 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql4
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:29 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:30 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql5
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:31 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:31 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql6
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:32 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:33 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql7
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:34 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:34 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql8
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:35 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:35 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-sql9
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:36 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:37 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-tersort
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:38 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:38 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info big-data-hadoop-spark-wordcount
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:39 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:40 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info cloud-compute-kvm-host
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:41 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:41 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-mariadb-2p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:42 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:42 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-mariadb-4p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:43 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:44 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-mongodb-2p-sysbench
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:45 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:45 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-mysql-2p-sysbench-hdd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:46 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:47 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-mysql-2p-sysbench-ssd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:48 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:48 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-postgresql-2p-sysbench-hdd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:49 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:49 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info database-postgresql-2p-sysbench-ssd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:50 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:51 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info default-default
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:52 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:52 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info docker-mariadb-2p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:53 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:54 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info docker-mariadb-4p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:54 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:55 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info hpc-gatk4-human-genome
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:56 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:56 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info in-memory-database-redis-redis-benchmark
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:57 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:58 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info middleware-dubbo-dubbo-benchmark
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:21:58 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:21:59 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info storage-ceph-vdbench-hdd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:00 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:00 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info storage-ceph-vdbench-ssd
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:01 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:02 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info virtualization-consumer-cloud-olc
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:03 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:03 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info virtualization-mariadb-2p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:04 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:05 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info virtualization-mariadb-4p-tpcc-c3
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:06 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:06 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info web-apache-traffic-server-spirent-pingpo
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:07 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:07 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info web-nginx-http-long-connection
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:08 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:09 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info web-nginx-https-short-connection
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep '.*A-Tune configuration' temp.log
+ CHECK_RESULT 1 0 0 'The output is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The output is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The output is not 0'
+ LOG_ERROR 'The output is not 0'
+ message='The output is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The output is not 0'
Thu May 25 22:22:10 2023 - ERROR - The output is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_01.sh line 33'
+ message='oe_test_service_atuned_01.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_01.sh line 33'
Thu May 25 22:22:10 2023 - ERROR - oe_test_service_atuned_01.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm info -h
+ grep 'display profile info corresponding to profile' temp.log
   display profile info corresponding to profile
+ CHECK_RESULT 0 0 0 'atune-adm info -h command execution failed. Procedure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-adm info -h command execution failed. Procedure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ atune-adm info
atune-adm: "info" requires exactly 1 argument(s)
+ grep 'Incorrect Usage.' temp.log
Incorrect Usage.
+ CHECK_RESULT 0 0 0 'atune-adm info command execution failed. Procedure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-adm info command execution failed. Procedure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 47
+ test 47 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 22:22:11 2023 - ERROR - failed to execute the case.
+ exit 47
+ post_test
+ clean_autund
+ systemctl stop atuned
+ systemctl stop atune-engine
+ rm -fr /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf
+ mv /etc/atuned/atuned.cnf.bak /etc/atuned/atuned.cnf
+ mv /etc/atuned/engine.cnf.bak /etc/atuned/engine.cnf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpbk8ahrtn ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpbk8ahrtn
+ '[' 0 -ne 0 ']'
+ rm -fr temp.log
